---
glob: '**/*.{html,text,js}{+*,}.erb'
exclude:
  - '**/vendor/**/*'
  - '**/node_modules/**/*'
linters:
  Rubocop:
    enabled: true
    rubocop_config:
      inherit_from:
        - .rubocop.yml
      Style/FrozenStringLiteralComment:
        Enabled: false
