version: '3'

volumes:
  pgdata:

services:
  postgres:
    image: postgres:latest
    env_file: ./docker/docker.env
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - '6379:6379'
