name: Tests

on:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CC_TEST_REPORTER_ID: 3ab5b0fb05090ad19926f86753ee7e0bc4c76ffef8477a63c09bcbcba5737a1a
      RAILS_ENV: test

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v2

      - name: Install PostgreSQL client
        run: |
          sudo apt-get -yqq install libpq-dev

      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Build App
        run: |
          mv config/database.cicd.yml config/database.yml
          bin/rails db:setup
          bin/rails webpacker:compile

      - name: Code Climate - Prebuild
        run: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
          chmod +x ./cc-test-reporter
          ./cc-test-reporter before-build

      - name: Run Tests
        run: |
          bundle exec rspec

      - name: Code Climate - Postbuild
        run: |
          ./cc-test-reporter after-build --exit-code 0
